service_name: sasuke
host: localhost
port: 50051
loglevel: DEBUG
private_key_path: ./res/sharingan_key.pem
rate_limiter:
  interval: 5m
  limit: 5
database:
  type: mongo
  mongodb_config:
    dsn: "mongodb://localhost:27017/sasukeDB"
    database_name: sasukeDB
    timeout: 10s
    valid_collections:
      - users
    valid_fields:
      - username
      - hashed_password
    mongo_server_options:
      api_version: 1
      set_strict: true
      set_deprecation_errors: true
