// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDocument creates a new instance of MockDocument. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocument(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocument {
	mock := &MockDocument{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDocument is an autogenerated mock type for the Document type
type MockDocument struct {
	mock.Mock
}

type MockDocument_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocument) EXPECT() *MockDocument_Expecter {
	return &MockDocument_Expecter{mock: &_m.Mock}
}
