// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoggerInterface creates a new instance of MockLoggerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerInterface {
	mock := &MockLoggerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoggerInterface is an autogenerated mock type for the LoggerInterface type
type MockLoggerInterface struct {
	mock.Mock
}

type MockLoggerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerInterface) EXPECT() *MockLoggerInterface_Expecter {
	return &MockLoggerInterface_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLoggerInterface
func (_mock *MockLoggerInterface) Debug(msg string, keyvals ...interface{}) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLoggerInterface_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLoggerInterface_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - keyvals ...interface{}
func (_e *MockLoggerInterface_Expecter) Debug(msg interface{}, keyvals ...interface{}) *MockLoggerInterface_Debug_Call {
	return &MockLoggerInterface_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLoggerInterface_Debug_Call) Run(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLoggerInterface_Debug_Call) Return() *MockLoggerInterface_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerInterface_Debug_Call) RunAndReturn(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLoggerInterface
func (_mock *MockLoggerInterface) Error(msg string, keyvals ...interface{}) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLoggerInterface_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLoggerInterface_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - keyvals ...interface{}
func (_e *MockLoggerInterface_Expecter) Error(msg interface{}, keyvals ...interface{}) *MockLoggerInterface_Error_Call {
	return &MockLoggerInterface_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLoggerInterface_Error_Call) Run(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLoggerInterface_Error_Call) Return() *MockLoggerInterface_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerInterface_Error_Call) RunAndReturn(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLoggerInterface
func (_mock *MockLoggerInterface) Info(msg string, keyvals ...interface{}) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLoggerInterface_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLoggerInterface_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - keyvals ...interface{}
func (_e *MockLoggerInterface_Expecter) Info(msg interface{}, keyvals ...interface{}) *MockLoggerInterface_Info_Call {
	return &MockLoggerInterface_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLoggerInterface_Info_Call) Run(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLoggerInterface_Info_Call) Return() *MockLoggerInterface_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerInterface_Info_Call) RunAndReturn(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Info_Call {
	_c.Run(run)
	return _c
}

// SetLevel provides a mock function for the type MockLoggerInterface
func (_mock *MockLoggerInterface) SetLevel(level string) {
	_mock.Called(level)
	return
}

// MockLoggerInterface_SetLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLevel'
type MockLoggerInterface_SetLevel_Call struct {
	*mock.Call
}

// SetLevel is a helper method to define mock.On call
//   - level string
func (_e *MockLoggerInterface_Expecter) SetLevel(level interface{}) *MockLoggerInterface_SetLevel_Call {
	return &MockLoggerInterface_SetLevel_Call{Call: _e.mock.On("SetLevel", level)}
}

func (_c *MockLoggerInterface_SetLevel_Call) Run(run func(level string)) *MockLoggerInterface_SetLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoggerInterface_SetLevel_Call) Return() *MockLoggerInterface_SetLevel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerInterface_SetLevel_Call) RunAndReturn(run func(level string)) *MockLoggerInterface_SetLevel_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLoggerInterface
func (_mock *MockLoggerInterface) Warn(msg string, keyvals ...interface{}) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLoggerInterface_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLoggerInterface_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - keyvals ...interface{}
func (_e *MockLoggerInterface_Expecter) Warn(msg interface{}, keyvals ...interface{}) *MockLoggerInterface_Warn_Call {
	return &MockLoggerInterface_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLoggerInterface_Warn_Call) Run(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLoggerInterface_Warn_Call) Return() *MockLoggerInterface_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerInterface_Warn_Call) RunAndReturn(run func(msg string, keyvals ...interface{})) *MockLoggerInterface_Warn_Call {
	_c.Run(run)
	return _c
}
