name: reviewdog
on: [pull_request]
env:
  REVIEWDOG_FAIL_ON_ERROR: 'true'
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Run unit tests
        run: |
          make unittest