name: Vulnerability Scan

on: [pull_request]

jobs:
  grype-scan:
    name: grype scan

    permissions:
      contents: read
      security-events: write
      actions: read
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: anchore/scan-action@v6
        with:
          path: "."
          fail-build: true